---
- hosts: pi
  remote_user: pi

  vars:
    root_path: /home/pi/mesi-io
    app_path: "{{ root_path }}/is4"
    container_name: mesi-io-is4

  tasks:

    - name: stop app
      shell: (docker kill {{ container_name }} || /bin/true) && (docker rm {{ container_name }} || /bin/true)

    - name: clean
      shell: find {{ app_path }} -type f ! -name 'log*' -delete || /bin/true

    - name: create directory
      file:
        path: "{{ root_path }}"
        state: directory
        mode: 0740

    - name: copy and extract app
      unarchive:
        src: is4.zip
        dest: "{{ root_path }}"
        mode: 0500

    - name: build app
      shell: docker build -t mesi/is4 {{ app_path }}
    
    - name: run app
      shell: docker run --name {{ container_name }} -d -p 14000:5000 -v {{ app_path }}/logs:/app/logs -e MESI_IO_IDENTITY_SERVER_ConnectionStrings__UserDatabase -e ASPNETCORE_Kestrel__Certificates__Default__Password="password" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ mesi/is4