---
- hosts: pi
  remote_user: pi

  vars:
    app_path: /var/www/mesi.io.is4

  tasks:

    - name: clean application
      shell: find {{ app_path }} -type f ! -name 'log*' -delete || /bin/true

    - name: delete service file
      shell: rm -f /etc/systemd/system/mesi.io.is4.service || /bin/true
      become: yes
      become_method: sudo

    - name: copy service file
      copy:
        src: ./systemd/mesi.io.is4.service
        dest: /etc/systemd/system
      become: yes
      become_method: sudo

    - name: copy application
      copy:
        src: "{{ item }}"
        dest: "{{ app_path }}"
        owner: pi
        group: pi
        mode: 0500
      with_fileglob:
        - "./publish/*"

    - name: start service
      systemd:
        name: mesi.io.is4
        state: restarted
        daemon_reload: yes
      become: yes
      become_method: sudo
