version: '3.7'

services:

  mesi-io-is4:
    image: mesi/is4
    container_name: mesi-io-is4

    ports:
      - 40300:5000
      
    volumes:
      - ./logs:/app/logs

    environment:
      - MESI_IO_IDENTITY_SERVER_ConnectionStrings__UserDatabase

    healthcheck:
      test: curl -f http://localhost:5000/heartbeat || exit 1
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 1m